/*
 * TELEXi Eurorack Module
 * (c) 2016 Brendon Cassidy
 * MIT License
 */
 
#ifndef Quantizer_h
#define Quantizer_h

#include "Arduino.h"

#define NOTES 128
#define NOTEEND 127
#define SCALES 1


struct QuantizeResponse {
  int Value;
  int Note; 
};

/*
 * Quantizes values 0-16383 to various tuning systems
 * created for the TELEX modules
 * some of this class is auto-generated by the associated python scripts
 */
class Quantizer
{
  public:

    Quantizer();
    Quantizer(int scale);
    QuantizeResponse Quantize(int in);
    void SetScale(int scale);
    float GetValueForNote(int note);
    float GetFrequencyForNote(int note);

  protected:

    // INSERT AUTOGENERATED SCALE HEADER DATA HERE
    
    const static int scaleCount = 22;
    static int *hints[22];
    static float *scales[22];
    static int notecount[22];
    
    static float scale0[122];
    static int hints0[122];
    static float scale1[122];
    static int hints1[122];
    static float scale2[172];
    static int hints2[172];
    static float scale3[122];
    static int hints3[122];
    static float scale4[155];
    static int hints4[155];
    static float scale5[190];
    static int hints5[190];
    static float scale6[343];
    static int hints6[343];
    static float scale7[122];
    static int hints7[122];
    static float scale8[122];
    static int hints8[122];
    static float scale9[122];
    static int hints9[122];
    static float scale10[122];
    static int hints10[122];
    static float scale11[122];
    static int hints11[122];
    static float scale12[122];
    static int hints12[122];
    static float scale13[122];
    static int hints13[122];
    static float scale14[122];
    static int hints14[122];
    static float scale15[432];
    static int hints15[432];
    static float scale16[392];
    static int hints16[392];
    static float scale17[372];
    static int hints17[372];
    static float scale18[292];
    static int hints18[292];
    static float scale19[222];
    static int hints19[222];
    static float scale20[92];
    static int hints20[92];
    static float scale21[123];
    static int hints21[123];

    // END AUTOGENERATED SCALE HEADER DATA
      
  private:
  
    int _scale;
    int _octave;
    int _index;
    int _nudge;
    int _above;
    int _below;
    int _current;
    QuantizeResponse _last;
    bool _noteMode;

};

#endif

