/*
 * TELEXo Eurorack Module
 * (c) 2016 Brendon Cassidy
 * MIT License
 */
 
#ifndef Quantizer_h
#define Quantizer_h

#include "Arduino.h"

#define NOTES 128
#define NOTEEND 127
#define SCALES 1

struct QuantizeResponse {
  int Note; 
  int Value;
  float Frequency;
};

/*
 * Quantizes values 0-16383 to various tuning systems
 * created for the TELEX modules
 * some of this class is auto-generated by the associated python scripts
 */
class Quantizer
{
  public:

    Quantizer();
    Quantizer(int scale);
    QuantizeResponse Quantize(int in);
    void SetScale(int scale);
    float GetValueForNote(int note);
    float GetFrequencyForNote(int note);

  protected:

    // INSERT AUTOGENERATED SCALE HEADER DATA HERE
  const static int scaleCount = 17;
  static const int *hints[17];
  static const float *scales[17];
  static const float *freqs[17];
  static const int notecount[17];
  
  static const float scale0[122];
  static const float freqs0[122];
  static const int hints0[122];
  static const float scale1[122];
  static const float freqs1[122];
  static const int hints1[122];
  static const float scale2[122];
  static const float freqs2[122];
  static const int hints2[122];
  static const float scale3[122];
  static const float freqs3[122];
  static const int hints3[122];
  static const float scale4[155];
  static const float freqs4[155];
  static const int hints4[155];
  static const float scale5[190];
  static const float freqs5[190];
  static const int hints5[190];
  static const float scale6[343];
  static const float freqs6[343];
  static const int hints6[343];
  static const float scale7[122];
  static const float freqs7[122];
  static const int hints7[122];
  static const float scale8[122];
  static const float freqs8[122];
  static const int hints8[122];
  static const float scale9[122];
  static const float freqs9[122];
  static const int hints9[122];
  static const float scale10[122];
  static const float freqs10[122];
  static const int hints10[122];
  static const float scale11[122];
  static const float freqs11[122];
  static const int hints11[122];
  static const float scale12[122];
  static const float freqs12[122];
  static const int hints12[122];
  static const float scale13[122];
  static const float freqs13[122];
  static const int hints13[122];
  static const float scale14[432];
  static const float freqs14[432];
  static const int hints14[432];
  static const float scale15[222];
  static const float freqs15[222];
  static const int hints15[222];
  static const float scale16[123];
  static const float freqs16[123];
  static const int hints16[123];

// END AUTOGENERATED SCALE HEADER DATA
      
  private:
  
    int _scale;
    int _octave;
    int _index;
    int _nudge;
    int _above;
    int _below;
    int _current;
    QuantizeResponse _last;
    bool _noteMode;

    int _temp;

};

#endif

